image: gradle:6.9.1-jdk11-openj9

stages:
  - build
  - test
  - package
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle build
  artifacts:
    paths:
      - api/build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

cache:
  key: "$CI_COMMIT_REF_NAME"
  policy: pull
  paths:
    - build
    - .gradle

test:
  stage: test
  script: 
    - gradle test
  artifacts:
    when: always
    reports:
      junit: 
        - api/build/test-results/test/TEST-*.xml
        - domain/build/test-results/test/TEST-*.xml

jacocoTestReportAPI:
  stage: test
  script:
    - 'gradle test jacocoTestReport'
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' api/build/reports/jacoco/test/jacocoTestReport.csv
  artifacts:
    when: always
    reports:
    paths:
      - api/build/reports/jacoco/test/jacocoTestReport.csv
      - api/build/reports/jacoco/test/html/*

jacocoTestReportDomain:
  stage: test
  script:
    - 'gradle test jacocoTestReport'
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' domain/build/reports/jacoco/test/jacocoTestReport.csv 
  artifacts:
    when: always
    reports:
    paths:
      - domain/build/reports/jacoco/test/jacocoTestReport.csv
      - domain/build/reports/jacoco/test/html/*

package:
  image: docker:latest
  services: 
    - docker:dind
  stage: package
  script:
    - docker build -t git.sogyo.nl:5050/gvdwel/mancala-java .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.sogyo.nl:5050
    - docker push git.sogyo.nl:5050/gvdwel/mancala-java

deploy_staging:
  stage: deploy
  image: docker:latest
  services: 
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.sogyo.nl:5050
    - docker pull git.sogyo.nl:5050/gvdwel/mancala-java:latest
    - docker run --rm -i -p 4200:80 git.sogyo.nl:5050/gvdwel/mancala-java:latest
  only:
    #naar mvc
    - mvc
    

deploy_staging:
  stage: deploy
  image: docker:latest
  services: 
    - docker:dind
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.sogyo.nl:5050
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker pull git.sogyo.nl:5050/gvdwel/mancala-java
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER "docker container stop mancala_container && docker container rm mancala_container || true"
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker run --name mancala_container -p 80:80 -d git.sogyo.nl:5050/gvdwel/mancala-java
  environment:
    name: staging
    url: https://testmancala.com
  only:
    #naar mvc
    - master

